-- V10: Add tagline column to diagnostic_reports
--
-- Supports the new AI report generation schema (Prompt B).
-- The tagline is the one-sentence candidate situation characterization
-- generated by the AI or template fallback.
-- Stored separately for efficient display without JSON parsing.
--
-- report_status valid values (post V10):
--   GENERATED    = AI Prompt B succeeded
--   RULE_BASED   = Template fallback used
--   REVIEWED     = Admin reviewed
--   PUBLISHED    = Published to candidate
--   FAILED       = Generation failure state

ALTER TABLE diagnostic_reports
    ADD COLUMN IF NOT EXISTS tagline TEXT;
