-- ============================================================
-- V2 — Create payment_transactions table
--
-- Immutable audit trail of every payment attempt. A new row
-- is inserted for each attempt; never updated in place except
-- to record gateway callbacks (status, gateway_payment_id, etc.).
--
-- candidate_profile_id is nullable for the initial row that is
-- created before the profile is fully submitted (initiate-first flow).
--
-- Indexes:
--   idx_pt_payment_reference — unique reference generated by backend
--   idx_pt_candidate_profile_id — list all txns for a candidate
--   idx_pt_gateway_order_id  — reconcile with gateway webhook
--   idx_pt_status            — filter by payment state
-- ============================================================

CREATE TABLE IF NOT EXISTS payment_transactions (
    id                   UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_reference    VARCHAR(60)    NOT NULL UNIQUE,
    candidate_profile_id UUID           REFERENCES candidate_profiles (id) ON DELETE SET NULL,
    gateway_name         VARCHAR(40)    NOT NULL,
    amount               NUMERIC(12, 2) NOT NULL,
    currency             VARCHAR(5)     NOT NULL DEFAULT 'INR',
    status               VARCHAR(20)    NOT NULL DEFAULT 'INITIATED'
                             CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'VERIFIED', 'REFUNDED')),
    gateway_order_id     VARCHAR(100),
    gateway_payment_id   VARCHAR(100),
    gateway_signature    VARCHAR(512),
    raw_payload          JSONB,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pt_payment_reference    ON payment_transactions (payment_reference);
CREATE        INDEX IF NOT EXISTS idx_pt_candidate_profile_id ON payment_transactions (candidate_profile_id);
CREATE        INDEX IF NOT EXISTS idx_pt_gateway_order_id     ON payment_transactions (gateway_order_id);
CREATE        INDEX IF NOT EXISTS idx_pt_status               ON payment_transactions (status);

COMMENT ON TABLE  payment_transactions                   IS 'Audit trail of every payment attempt — append-mostly';
COMMENT ON COLUMN payment_transactions.payment_reference IS 'Backend-generated unique ref (e.g. PAY-20240101-XYZ)';
COMMENT ON COLUMN payment_transactions.raw_payload       IS 'Full gateway webhook or response payload for debugging';
