package com.qualscore.qualcore.enums;

public enum CrmTag {
    CAREER_CLARITY_LOW,
    JOB_SEARCH_INCONSISTENT,
    INTERVIEW_READINESS_LOW,
    FLEXIBILITY_LOW,
    HIGH_INTENT,
    WARM_LEAD,
    LOW_ACTION_INTENT,
    PROOF_OF_WORK_LOW,
    SALARY_EXPECTATION_RISK,
    CONSULTATION_PRIORITY,
    NURTURE_AFTER_REPORT,
    LOW_IMMEDIATE_CONVERSION,
    HIGH_PAIN_LEAD,
    WARM_DIAGNOSTIC_LEAD,
    PREMIUM_LEAD
}
