/*
  # Add prompt_version column to diagnostic_reports

  ## Purpose
  Track which version of the AI prompt was used to generate each report.
  This allows safe prompt tuning without retroactively confusing which
  reports were generated by which prompt version.

  ## Changes
  - `diagnostic_reports.prompt_version` (VARCHAR 20, nullable)
    - null = pre-versioning (generated before this migration)
    - 'B-1.0' = initial Prompt B baseline
    - 'B-1.1' = strengthened system prompt with explicit forbidden-language rules
    - future: 'B-2.0', etc.

  ## Notes
  - Nullable intentionally — existing rows retain null to distinguish from versioned ones
  - Prompt version is managed in PromptTemplateService.REPORT_PROMPT_VERSION constant
  - No default — only explicitly set during generation
*/

ALTER TABLE diagnostic_reports
    ADD COLUMN IF NOT EXISTS prompt_version VARCHAR(20);

COMMENT ON COLUMN diagnostic_reports.prompt_version IS 'Prompt B version used for AI generation, e.g. B-1.1. Null = pre-versioning or rule-based.';
